#!/usr/bin/env php
<?php
use Pine\Application;
use Phalcon\Di\FactoryDefault\Cli as CliDi;

$di = new CliDi();

$app = new Application(__DIR__, $di);

$app->bootstrap();

$application = new Symfony\Component\Console\Application();

$di->setShared("console", $application);

try {
    $app->runCommand();
} catch (Throwable $e) {
    echo $e->getMessage();
}
